package vista;

import datos.ManejaDatosHongo;
import modelo.ComunicaHongoConDatos;
import modelo.Hongo;
import modelo.Usuario;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

public class ListaHongos extends JDialog {
    private JPanel panel1;
    private JList listaHongos;
    String[] data = {"one", "two", "three", "four"};

    public ListaHongos(BuscarHongos parent, boolean modal) {
        // Tamaño de la ventana
        super (parent, modal);
        $$$setupUI$$$ ();
        this.setMinimumSize (new Dimension (500, 500));
        this.setPreferredSize (new Dimension (500, 500));
        this.setMaximumSize (new Dimension (500, 500));
        parent.setVisible (false);
        setTitle ("Lista de Hongos");
        setLocationRelativeTo (null); // Se abre por default a la mitad de la pantalla.
        this.setContentPane (panel1);
        this.pack ();
        setDefaultCloseOperation (HIDE_ON_CLOSE);
        ListaHongos listaHongos = this;
        this.addWindowListener (new WindowAdapter () {
            public void windowClosing(WindowEvent e) {
                parent.setVisible (true);
            }

        });

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel ();
        panel1.setLayout (new com.intellij.uiDesigner.core.GridLayoutManager (1, 1, new Insets (0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel ();
        panel2.setLayout (new com.intellij.uiDesigner.core.GridLayoutManager (2, 1, new Insets (0, 0, 0, 0), -1, -1));
        panel1.add (panel2, new com.intellij.uiDesigner.core.GridConstraints (0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel ();
        label1.setText ("Lista completa de Hongos");
        panel2.add (label1, new com.intellij.uiDesigner.core.GridConstraints (0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        listaHongos = new JList ();
        listaHongos.setLayoutOrientation (2);
        final DefaultListModel defaultListModel1 = new DefaultListModel ();
        defaultListModel1.addElement ("data");
        listaHongos.setModel (defaultListModel1);
        listaHongos.setSelectionMode (2);
        panel2.add (listaHongos, new com.intellij.uiDesigner.core.GridConstraints (1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension (150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        DefaultListModel dlm = new DefaultListModel ();
        ArrayList<Hongo> hongos = ComunicaHongoConDatos.obtenerHongos ();

        for (Hongo hongo :
                hongos) {
            System.out.println (hongo.getNombre ());
            dlm.addElement (hongo.getNombre ());
        }

        JList<String> listaHongosPrueba = new JList<> (dlm);
    }
}
